version: '3.8'
services:
  auth-service:
    image: yourdockerhub/auth-service:latest
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - LOKI_URL=${LOKI_URL}
    env_file:
      - .env
  payment-service:
    image: yourdockerhub/payment-service:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - LOKI_URL=${LOKI_URL}
    env_file:
      - .env
  analytics-service:
    image: yourdockerhub/analytics-service:latest
    ports:
      - "8081:8081"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - LOKI_URL=${LOKI_URL}
    env_file:
      - .env
  realtime-service:
    image: yourdockerhub/realtime-service:latest
    ports:
      - "3000:3000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - LOKI_URL=${LOKI_URL}
    env_file:
      - .env
  billing-service:
    image: yourdockerhub/billing-service:latest
    ports:
      - "3003:3003"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - LOKI_URL=${LOKI_URL}
      - MONGODB_URL=${MONGODB_URL}
    env_file:
      - .env
  project-service:
    image: yourdockerhub/project-service:latest
    ports:
      - "3004:3004"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - LOKI_URL=${LOKI_URL}
      - MONGODB_URL=${MONGODB_URL}
    env_file:
      - .env
  communication-service:
    image: yourdockerhub/communication-service:latest
    ports:
      - "3005:3005"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - LOKI_URL=${LOKI_URL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    env_file:
      - .env
  ai-service:
    image: yourdockerhub/ai-service:latest
    ports:
      - "3006:3006"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - PROMETHEUS_URL=${PROMETHEUS_URL}
      - LOKI_URL=${LOKI_URL}
      - MONGODB_URL=${MONGODB_URL}
    env_file:
      - .env
  admin:
    image: yourdockerhub/admin:latest
    ports:
      - "3002:3002"
    environment:
      - NEXT_PUBLIC_PROMETHEUS_URL=${PROMETHEUS_URL}
      - NEXT_PUBLIC_GRAFANA_URL=${GRAFANA_URL}
      - NEXT_PUBLIC_LOKI_URL=${LOKI_URL}
      - NEXT_PUBLIC_JAEGER_URL=${JAEGER_URL}
    env_file:
      - .env
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./gitops/manifests/prometheus.yaml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=${GRAFANA_URL}
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
