apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

../../manifests/auth-service-rollout.yaml
../../manifests/payment-service-rollout.yaml
../../manifests/analytics-service-rollout.yaml
../../manifests/realtime-service-rollout.yaml
../../manifests/billing-service-rollout.yaml
../../manifests/project-service-rollout.yaml
../../manifests/communication-service-rollout.yaml
../../manifests/ai-service-rollout.yaml images:
name: yourdockerhub/auth-service newTag: latest
name: yourdockerhub/payment-service newTag: latest
name: yourdockerhub/analytics-service newTag: latest
name: yourdockerhub/realtime-service newTag: latest
name: yourdockerhub/billing-service newTag: latest
name: yourdockerhub/project-service newTag: latest
name: yourdockerhub/communication-service newTag: latest
name: yourdockerhub/ai-service newTag: latest namespace: dev
